### ISSUE TITLE
Dependency on blanc

### ISSUE THREAD

**Issue by sangttruong** [stair-lab/melt#3]
What is the reason for including the source code of [blanc](https://github.com/PrimerAI/blanc) in the code? Which commit did you copy the code from?

**Comment by martinakaduc** [comment]
The reason for this blanc (original source: https://github.com/PrimerAI/blanc) being here is that it requires torch < 2.0. However, it can run with the latest torch version.
We can have a better solution by forking the original repository and making the changes on our fork instead of creating a PR, as I have not seen any activity on this repo for more than six months.

**Comment by sangttruong** [comment]
If the development of the package has been stopped, you might want to remove dependences on it all together. What is the main utility of this package?

**Comment by martinakaduc** [comment]
It is used to compute three summarization metrics which are not in Huggingface including coverage, density and compression.

**Comment by sangttruong** [comment]
Can you just reimplement these 3 metrics? These 3 metrics don’t seem to justify the dependency of a deprecating package.

**Comment by martinakaduc** [comment]
I think it is not that ease. I will investigate and get back later.

**Comment by ledong0110** [comment]
Hi, please check my implementation in PR #4
